# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Miestas', 'verbose_name_plural': 'Miestai'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Mikrorajonas', 'verbose_name_plural': 'Mikrorajonai'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Savanoris', 'verbose_name_plural': 'Savanoriai'},
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.City'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='Miestas'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.District', verbose_name='Mikrorajonas'),
        ),
    ]
