# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20151230_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=255, verbose_name='Apskritis')),
                ('municipality', models.CharField(max_length=255, verbose_name='Savivaldybė')),
                ('eldership', models.CharField(max_length=255, verbose_name='Seniūnija')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('osm_id', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=255, verbose_name='Gyvenvietė')),
                ('population', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('wikipedia_lang', models.CharField(max_length=10)),
                ('wikipedia_title', models.CharField(max_length=255)),
            ],
        ),
    ]
