# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160101_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='district',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Place', verbose_name='Vieta'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
