# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160101_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('visible', models.BooleanField(default=True, verbose_name='Rodoma')),
            ],
            options={
                'verbose_name_plural': 'Pamainos',
                'verbose_name': 'Pamaina',
            },
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='shift',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='shift',
            field=models.ManyToManyField(null=True, to='core.Shift', verbose_name='Pamainos'),
        ),
    ]
