# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20160101_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Pradžia')),
                ('end_date', models.DateField(verbose_name='Pabaiga')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefonas')),
                ('places', models.ManyToManyField(to='core.Place', verbose_name='Vietos')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Užsiregistravo')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaign', verbose_name='Akcija')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organisation', verbose_name='Organizacija')),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telefonas'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='shift',
            field=models.ManyToManyField(to='core.Shift', verbose_name='Pamainos'),
        ),
        migrations.AddField(
            model_name='volunteercampaign',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Volunteer', verbose_name='Savanoris'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='campaigns',
            field=models.ManyToManyField(editable=False, through='core.VolunteerCampaign', to='core.Campaign', verbose_name='Akcijos'),
        ),
    ]
