# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160102_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Patirtis'),
        ),
    ]
