# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160123_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='place',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='places',
            field=models.ManyToManyField(to='core.Place', verbose_name='Vietos'),
        ),
    ]
