# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160123_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Akcija', 'verbose_name_plural': 'Akcijos'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktyvi'),
        ),
    ]
