# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160124_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteercampaign',
            name='accepted',
            field=models.NullBooleanField(verbose_name='Priimta'),
        ),
        migrations.AddField(
            model_name='volunteercampaign',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='Pašalinta organizacijos'),
        ),
    ]
