# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160124_2047'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteercampaign',
            unique_together=set([('volunteer', 'campaign', 'organisation')]),
        ),
    ]
